export const SEARCH_MOVIES = 'SEARCH_MOVIES';
export const CLEAR_MOVIES = 'CLEAR_MOVIES';
export const MOVIES_ERROR = 'MOVIES_ERROR';
export const ADD_NOMINATION = 'ADD_NOMINATION';
export const DELETE_NOMINATION = 'DELETE_NOMINATION';
export const SET_LOADING = 'SET_LOADING';
